wandb:
  entity: null
  resume: 'auto'


# only need to be set when using multi-nodes
system:
    HTTP_PROXY: "http://100.68.168.184:3128"
    HF_HOME: "/data_storage/wyj/systems/huggingface"
    env_name: "CURE"
    envs_dir: "/data_storage/wyj/systems/envs"
    base_dir: "/data_storage/wyj/DLM/DLLM-RL"

experiment:
    project: "multinode_rl_sdar_with_value"
    function: "train"
    start_from_scratch: True
    total_step: 200
    save_every: 50
    eval_every: 5
    train_value_every: 1
    current_epoch: 1
    deepspeed_file: "8_node_8_gpus_deepspeed_zero3"
    num_node: 8
    node_index: 0

model:
    pretrained_model: "/data_storage/wyj/systems/huggingface/hub/models--JetLM--SDAR-8B-Chat/snapshots/de54a3350737454faabc3ddb40b8119866cc6ebd"
    value_base_model: "/data_storage/wyj/systems/huggingface/hub/models--JetLM--SDAR-8B-Chat/snapshots/de54a3350737454faabc3ddb40b8119866cc6ebd"
    optimized_name: "optimized3"
    optimized_value_name: "optimized_value3"
    model_base: "sdar"

# "/data_storage/wyj/systems/huggingface/hub/models--JetLM--SDAR-8B-Chat/snapshots/de54a3350737454faabc3ddb40b8119866cc6ebd"
# "/data_storage/wyj/systems/huggingface/hub/models--JetLM--SDAR-4B-Chat/snapshots/824f7ab513778bd93ce9f0f9039b9ee56b23c250"
# "/data_storage/wyj/systems/huggingface/hub/models--JetLM--SDAR-1.7B-Chat/snapshots/553d10acb7a3e09fec332c38cfd5610811f27776"



dataset:
    train_dataset: "MATH_train"
    optimization_data: "rl_data"
    data_type: "math"


rollout:
    tensor_parallel_size: 1
    max_active: 256
    num_task_per_step: 128
    num_response_per_task: 32
    temperature: 1.0
    max_token: 2000
    block_size: 4
    denoising_steps_per_block: 4
    top_p: 1.0
    top_k: 0
    remasking_strategy: "low_confidence_dynamic" #"low_confidence_static""low_confidence_dynamic"
    dynamic_threshold: 0.9 # no use for "low_confidence_static"

execute:
    num_chunk: 256 # batch size of executing codes in coding eval tasks

training:
    gradient_checkpointing_enable: True
    gradient_accumulation_steps: 4
    batch_size_lm: 1
    mixed_precision: "bf16"
    enable_tf32: True
    seed: 10086
    num_train_epochs: 1
    max_grad_norm: 1.0
    method: "TraceRL"
    block_size: 4
    shrink: 1
    post_num: 0
    max_gen_length: 1600
    max_prompt_len: 784
    eps: 0.20
    beta: 0.01
    gam: 1.0
    lam: 1.0
    use_kl_estimator_k3: True


optimizer:
    name: adamw
    params: # default adamw params
        policy_learning_rate: 1e-6
        value_learning_rate: 5e-6
        scale_lr: False # scale learning rate by total batch size
        beta1: 0.9
        beta2: 0.999
        weight_decay: 0.0
        epsilon: 1e-8


lr_scheduler:
    scheduler: "cosine"
    params:
        learning_rate: ${optimizer.params.policy_learning_rate}
        warmup_steps: 0
        min_lr_scale: 1.0


evaluation:
    eval_dataset: "MATH500"
    data_type: "math"
    tensor_parallel_size: 1
    max_active: 256
    num_response_per_task: 3
    temperature: 1.0
    max_token: 2000
    block_size: 4
    denoising_steps_per_block: 4
    top_p: 1.0
    top_k: [0, 1]
    remasking_strategy: ["low_confidence_dynamic", "low_confidence_static"] #"low_confidence_static""low_confidence_dynamic"
    dynamic_threshold: 0.9 # no use for "low_confidence_static"


